language: node_js
node_js: stable
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "2X-ercha"
  - git config user.email "noionion@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${travis}@${GH_REF}" master:master
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com:2X-ercha/2X-ercha.github.io.git
